name: main
on:
  push:
    branch:
      - main

jobs:

  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Operator SDK
        uses: ./actions/setup-operator-sdk
      - name: Check Operator SDK
        run: |
          operator-sdk --help
